### ISSUE TITLE
Color Scheme Not Loading Properly

### ISSUE THREAD

**Issue by Hovden** [Hovden/cornell-spectrum-imager#2]
The colors in CSI spectrum imager do not work for the most recent versions of ImageJ.

**Comment by Hovden** [comment]
Relevant code is in SpectrumData.java

Problem is due to the depreciated Plot.LEFT_MARGIN and Plot.TOP_MARGIN

ff.fill(Plot.LEFT_MARGIN + (plotWidth) / 2, Plot.TOP_MARGIN + 1);
ff.fill(Plot.LEFT_MARGIN + (plotWidth) / 2, plotHeight - 1);

**Comment by pdcueva** [comment]
Filling in the data is no longer feasible. Color sets have been adjusted accordingly.
